<a href="https://colab.research.google.com/github/w4ib4/2438446_SrijanTamang/blob/main/Worksheet0_SrijanTamang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
def convert_length(value, direction):
    """
    Converts length between meters and feet.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'm_to_ft' or 'ft_to_m'.

    Returns:
        float: The converted value.
    """
    if direction == 'm_to_ft':
        return value * 3.28084
    elif direction == 'ft_to_m':
        return value / 3.28084
    else:
        raise ValueError("Invalid direction. Use 'm_to_ft' or 'ft_to_m'.")


def convert_weight(value, direction):
    """
    Converts weight between kilograms and pounds.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'kg_to_lbs' or 'lbs_to_kg'.

    Returns:
        float: The converted value.
    """
    if direction == 'kg_to_lbs':
        return value * 2.20462
    elif direction == 'lbs_to_kg':
        return value / 2.20462
    else:
        raise ValueError("Invalid direction. Use 'kg_to_lbs' or 'lbs_to_kg'.")


def convert_volume(value, direction):
    """
    Converts volume between liters and gallons.

    Parameters:
        value (float): The numeric value to convert.
        direction (str): 'l_to_gal' or 'gal_to_l'.

    Returns:
        float: The converted value.
    """
    if direction == 'l_to_gal':
        return value * 0.264172
    elif direction == 'gal_to_l':
        return value / 0.264172
    else:
        raise ValueError("Invalid direction. Use 'l_to_gal' or 'gal_to_l'.")


def unit_converter():
    """
    Main function to interactively convert between units of measurement.
    Supports length (m/ft), weight (kg/lbs), and volume (L/gal).
    Handles invalid inputs using try-except blocks.

    Returns:
        float or None: The converted result, or None if input is invalid.
    """
    print("Unit Converter")
    print("Choose conversion type:")
    print("1. Length (meters <-> feet)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (liters <-> gallons)")

    choice = input("Enter 1, 2, or 3: ").strip()

    try:
        value = float(input("Enter the value to convert: "))
    except ValueError:
        print("Error: Please enter a valid numeric value.")
        return None

    try:
        if choice == '1':
            sub = input("Convert (1) m->ft or (2) ft->m? ")
            direction = 'm_to_ft' if sub == '1' else 'ft_to_m'
            result = convert_length(value, direction)
            unit_in = 'm' if sub == '1' else 'ft'
            unit_out = 'ft' if sub == '1' else 'm'
        elif choice == '2':
            sub = input("Convert (1) kg->lbs or (2) lbs->kg? ")
            direction = 'kg_to_lbs' if sub == '1' else 'lbs_to_kg'
            result = convert_weight(value, direction)
            unit_in = 'kg' if sub == '1' else 'lbs'
            unit_out = 'lbs' if sub == '1' else 'kg'
        elif choice == '3':
            sub = input("Convert (1) L->gal or (2) gal->L? ")
            direction = 'l_to_gal' if sub == '1' else 'gal_to_l'
            result = convert_volume(value, direction)
            unit_in = 'L' if sub == '1' else 'gal'
            unit_out = 'gal' if sub == '1' else 'L'
        else:
            print("Error: Unsupported conversion type.")
            return None

        print(f"Result: {value} {unit_in} = {result:.4f} {unit_out}")
        return result

    except ValueError as e:
        print(f"Conversion error: {e}")
        return None

print("Demo: convert_length(10, 'm_to_ft') =", convert_length(10, 'm_to_ft'))
print("Demo: convert_weight(70, 'kg_to_lbs') =", convert_weight(70, 'kg_to_lbs'))
print("Demo: convert_volume(5, 'l_to_gal') =", convert_volume(5, 'l_to_gal'))

Demo: convert_length(10, 'm_to_ft') = 32.8084
Demo: convert_weight(70, 'kg_to_lbs') = 154.3234
Demo: convert_volume(5, 'l_to_gal') = 1.3208600000000001


In [4]:
def compute_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
        numbers (list of float): The input list.

    Returns:
        float: Sum of all elements.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return sum(numbers)


def compute_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
        numbers (list of float): The input list.

    Returns:
        float: Average of all elements.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return sum(numbers) / len(numbers)


def compute_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
        numbers (list of float): The input list.

    Returns:
        float: Maximum element.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return max(numbers)


def compute_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
        numbers (list of float): The input list.

    Returns:
        float: Minimum element.
    """
    if not numbers:
        raise ValueError("List is empty.")
    return min(numbers)


def math_operations():
    """
    Interactively performs sum, average, max, or min on a user-provided list.
    Handles invalid inputs and empty lists with try-except blocks.

    Returns:
        float or None: The computed result, or None on error.
    """
    print("Mathematical Operations")
    print("1. Sum  2. Average  3. Maximum  4. Minimum")
    choice = input("Choose operation (1-4): ").strip()

    try:
        raw = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in raw.split()]
        if not numbers:
            raise ValueError("No numbers provided.")
    except ValueError as e:
        print(f"Input error: {e}")
        return None

    ops = {'1': compute_sum, '2': compute_average,
           '3': compute_maximum, '4': compute_minimum}
    names = {'1': 'Sum', '2': 'Average', '3': 'Maximum', '4': 'Minimum'}

    if choice not in ops:
        print("Invalid operation choice.")
        return None

    try:
        result = ops[choice](numbers)
        print(f"{names[choice]}: {result}")
        return result
    except ValueError as e:
        print(f"Error: {e}")
        return None

sample = [3.0, 7.5, 2.0, 9.0, 4.5]
print("Sample list:", sample)
print("Sum     :", compute_sum(sample))
print("Average :", compute_average(sample))
print("Maximum :", compute_maximum(sample))
print("Minimum :", compute_minimum(sample))

Sample list: [3.0, 7.5, 2.0, 9.0, 4.5]
Sum     : 26.0
Average : 5.2
Maximum : 9.0
Minimum : 2.0


In [5]:
# 1. Extract every other element
def extract_every_other(lst):
    """Returns every other element starting from index 0."""
    return lst[::2]

# 2. Slice a sublist (inclusive end)
def get_sublist(lst, start, end):
    """Returns elements from index start to end (inclusive)."""
    return lst[start:end + 1]

# 3. Reverse a list using slicing
def reverse_list(lst):
    """Returns a reversed copy of the list using slicing."""
    return lst[::-1]

# 4. Remove first and last elements
def remove_first_last(lst):
    """Returns the list without its first and last elements."""
    return lst[1:-1]

# 5. Get first n elements
def get_first_n(lst, n):
    """Returns the first n elements of the list."""
    return lst[:n]

# 6. Get last n elements
def get_last_n(lst, n):
    """Returns the last n elements of the list."""
    return lst[-n:]

# 7. Reverse skip: every second element starting from second-to-last, going backward
def reverse_skip(lst):
    """Returns every second element from second-to-last, moving backward."""
    return lst[-2::-2]
lst1 = [1, 2, 3, 4, 5, 6]
lst2 = [1, 2, 3, 4, 5]

print("extract_every_other([1,2,3,4,5,6]):", extract_every_other(lst1))   # [1,3,5]
print("get_sublist([1..6], 2, 4)         :", get_sublist(lst1, 2, 4))      # [3,4,5]
print("reverse_list([1,2,3,4,5])         :", reverse_list(lst2))           # [5,4,3,2,1]
print("remove_first_last([1,2,3,4,5])    :", remove_first_last(lst2))      # [2,3,4]
print("get_first_n([1,2,3,4,5], 3)       :", get_first_n(lst2, 3))         # [1,2,3]
print("get_last_n([1,2,3,4,5], 2)        :", get_last_n(lst2, 2))          # [4,5]
print("reverse_skip([1,2,3,4,5,6])       :", reverse_skip(lst1))           # [5,3,1]

extract_every_other([1,2,3,4,5,6]): [1, 3, 5]
get_sublist([1..6], 2, 4)         : [3, 4, 5]
reverse_list([1,2,3,4,5])         : [5, 4, 3, 2, 1]
remove_first_last([1,2,3,4,5])    : [2, 3, 4]
get_first_n([1,2,3,4,5], 3)       : [1, 2, 3]
get_last_n([1,2,3,4,5], 2)        : [4, 5]
reverse_skip([1,2,3,4,5,6])       : [5, 3, 1]


In [7]:
# 1. Flatten a nested list (one level deep)
def flatten(lst):
    """Flattens a one-level nested list into a single list."""
    return [item for sublist in lst for item in sublist]

# 2. Access nested element by a list of indices
def access_nested_element(lst, indices):
    """Returns the element in lst reached by following each index in indices."""
    element = lst
    for idx in indices:
        element = element[idx]
    return element

# 3. Sum of all elements in a nested list (any depth)
def sum_nested(lst):
    """Returns the sum of all numeric elements in a nested list of any depth."""
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# 4. Remove specific element from a nested list
def remove_element(lst, elem):
    """Removes all occurrences of elem from each sub-list."""
    return [[x for x in sublist if x != elem] for sublist in lst]

# 5. Find maximum element in nested list (any depth)
def find_max(lst):
    """Returns the maximum element in a nested list of any depth."""
    flat = []
    def _flatten(l):
        for item in l:
            if isinstance(item, list):
                _flatten(item)
            else:
                flat.append(item)
    _flatten(lst)
    return max(flat)

# 6. Count occurrences of an element in a nested list
def count_occurrences(lst, elem):
    """Counts how many times elem appears in a nested list."""
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# 7. Deep flatten (any depth)
def deep_flatten(lst):
    """Flattens a nested list of any depth into a single flat list."""
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

# 8. Average of all elements in a nested list
def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat = deep_flatten(lst)
    return sum(flat) / len(flat)

print("flatten([[1,2],[3,4],[5]])            :", flatten([[1,2],[3,4],[5]]))
print("access_nested_element, indices [1,2] :", access_nested_element([[1,2,3],[4,5,6],[7,8,9]], [1,2]))
print("sum_nested([[1,2],[3,[4,5]],6])       :", sum_nested([[1,2],[3,[4,5]],6]))
print("remove_element([[1,2],[3,2],[4,5]],2):", remove_element([[1,2],[3,2],[4,5]], 2))
print("find_max([[1,2],[3,[4,5]],6])         :", find_max([[1,2],[3,[4,5]],6]))
print("count_occurrences([[1,2],[2,3],[2,4]],2):", count_occurrences([[1,2],[2,3],[2,4]], 2))
print("deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]):", deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))
print("average_nested([[1,2],[3,4],[5,6]])   :", average_nested([[1,2],[3,4],[5,6]]))

flatten([[1,2],[3,4],[5]])            : [1, 2, 3, 4, 5]
access_nested_element, indices [1,2] : 6
sum_nested([[1,2],[3,[4,5]],6])       : 21
remove_element([[1,2],[3,2],[4,5]],2): [[1], [3], [4, 5]]
find_max([[1,2],[3,[4,5]],6])         : 6
count_occurrences([[1,2],[2,3],[2,4]],2): 3
deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]): [1, 2, 3, 4, 5, 6, 7, 8]
average_nested([[1,2],[3,4],[5,6]])   : 3.5


In [8]:
import numpy as np

# 1. Empty 2x2 array
empty_2x2 = np.empty((2, 2))
print("1. Empty 2x2:\n", empty_2x2)

# 2. All-ones 4x2 array
ones_4x2 = np.ones((4, 2))
print("\n2. Ones 4x2:\n", ones_4x2)

# 3. Array filled with a fill value (e.g., 7), shape 3x3
filled = np.full((3, 3), 7)
print("\n3. Full array (fill=7):\n", filled)

# 4. np.zeros_like
reference = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like = np.zeros_like(reference)
print("\n4. Zeros like reference array:\n", zeros_like)

# 5. np.ones_like
ones_like = np.ones_like(reference)
print("\n5. Ones like reference array:\n", ones_like)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("\n6. Array from list:", arr_from_list)

1. Empty 2x2:
 [[5.10187062e-315 0.00000000e+000]
 [4.94065646e-324 6.71991958e-310]]

2. Ones 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full array (fill=7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like reference array:
 [[0 0 0]
 [0 0 0]]

5. Ones like reference array:
 [[1 1 1]
 [1 1 1]]

6. Array from list: [1 2 3 4]


In [9]:
import numpy as np

# 1. Values 10 to 49
arr_10_49 = np.arange(10, 50)
print("1. Range 10-49:\n", arr_10_49)

# 2. 3x3 matrix, values 0-8
mat_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix (0-8):\n", mat_3x3)

# 3. 3x3 identity matrix
identity = np.eye(3)
print("\n3. 3x3 Identity matrix:\n", identity)

# 4. Random array of size 30, find mean
rand_30 = np.random.random(30)
print("\n4. Mean of random array (size 30):", rand_30.mean())

# 5. 10x10 random array, find min and max
rand_10x10 = np.random.random((10, 10))
print("\n5. 10x10 random array - min:", rand_10x10.min(), "  max:", rand_10x10.max())

# 6. Zero array of size 10, replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6. Zero array with 5th element = 1:\n", zero_arr)

# 7. Reverse array
arr_rev = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr_rev[::-1]
print("\n7. Reversed array:", reversed_arr)

# 8. 2D array with 1 on border and 0 inside
border_arr = np.ones((6, 6))
border_arr[1:-1, 1:-1] = 0
print("\n8. Border array:\n", border_arr)

# 9. 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerboard (8x8):\n", checkerboard)

1. Range 10-49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix (0-8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random array (size 30): 0.43548087779139466

5. 10x10 random array - min: 0.008406064097263521   max: 0.9802260349302927

6. Zero array with 5th element = 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. Border array:
 [[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]

9. Checkerboard (8x8):
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [10]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add
print("1. x + y =\n", x + y)

# 2. Subtract
print("\n2. x - y =\n", x - y)

# 3. Multiply by scalar
scalar = 3
print(f"\n3. x * {scalar} =\n", x * scalar)

# 4. Square each element
print("\n4. x squared =\n", np.square(x))

# 5. Dot products
print("\n5a. dot(v, w) =", np.dot(v, w))
print("5b. dot(x, v) =", np.dot(x, v))
print("5c. dot(x, y) =\n", np.dot(x, y))

# 6. Concatenate x and y along rows; v and w along columns
concat_xy_rows = np.vstack((x, y))
concat_vw_col  = np.concatenate((v, w))
print("\n6a. vstack(x, y) =\n", concat_xy_rows)
print("6b. concatenate(v, w) =", concat_vw_col)

# 7. Concatenate x and v — dimension mismatch error
print("\n7. Attempting np.concatenate(x, v):")
try:
    result = np.concatenate((x, v))
except ValueError as e:
    print(f"   Error: {e}")
    print("   Reason: x has shape", x.shape, "and v has shape", v.shape,
          "- they have different numbers of dimensions, so concatenation fails.")

1. x + y =
 [[ 6  8]
 [10 13]]

2. x - y =
 [[-4 -4]
 [-4 -3]]

3. x * 3 =
 [[ 3  6]
 [ 9 15]]

4. x squared =
 [[ 1  4]
 [ 9 25]]

5a. dot(v, w) = 219
5b. dot(x, v) = [29 77]
5c. dot(x, y) =
 [[19 22]
 [50 58]]

6a. vstack(x, y) =
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. concatenate(v, w) = [ 9 10 11 12]

7. Attempting np.concatenate(x, v):
   Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
   Reason: x has shape (2, 2) and v has shape (2,) - they have different numbers of dimensions, so concatenation fails.


In [11]:
import numpy as np

A = np.array([[3, 4], [7, 8]], dtype=float)
B = np.array([[5, 3], [2, 1]], dtype=float)

A_inv = np.linalg.inv(A)

# 1. Prove A * A^-1 = I
print("1. A @ A_inv (should be Identity):\n",
      np.round(A @ A_inv, decimals=10))

# 2. Prove AB != BA
AB = A @ B
BA = B @ A
print("\n2. AB =\n", AB)
print("   BA =\n", BA)
print("   AB == BA:", np.allclose(AB, BA))  # Should be False

# 3. Prove (AB)^T = B^T * A^T
lhs = (A @ B).T
rhs = B.T @ A.T
print("\n3. (AB)^T =\n", lhs)
print("   B^T @ A^T =\n", rhs)
print("   Equal:", np.allclose(lhs, rhs))  # Should be True

# ---- Solve system of linear equations ----
# 2x - 3y + z  = -1
# x  - y  + 2z = -3
# 3x + y  - z  =  9
coef = np.array([[ 2, -3,  1],
                 [ 1, -1,  2],
                 [ 3,  1, -1]], dtype=float)
b_vec = np.array([-1, -3, 9], dtype=float)

# Inverse method: X = A^-1 * B
coef_inv = np.linalg.inv(coef)
X_inv = coef_inv @ b_vec
print("\n--- System of Equations ---")
print("Solution via Inverse method (x, y, z):", np.round(X_inv, 4))

# Using np.linalg.solve
X_solve = np.linalg.solve(coef, b_vec)
print("Solution via linalg.solve  (x, y, z):", np.round(X_solve, 4))

# Verify
print("Verification A @ X =", np.round(coef @ X_solve, 4), " (should be", b_vec, ")")

1. A @ A_inv (should be Identity):
 [[1. 0.]
 [0. 1.]]

2. AB =
 [[23. 13.]
 [51. 29.]]
   BA =
 [[36. 44.]
 [13. 16.]]
   AB == BA: False

3. (AB)^T =
 [[23. 51.]
 [13. 29.]]
   B^T @ A^T =
 [[23. 51.]
 [13. 29.]]
   Equal: True

--- System of Equations ---
Solution via Inverse method (x, y, z): [ 2.  1. -2.]
Solution via linalg.solve  (x, y, z): [ 2.  1. -2.]
Verification A @ X = [-1. -3.  9.]  (should be [-1. -3.  9.] )


In [13]:
import numpy as np
import time

SIZE = 1_000_000

#Prepare data
py_a = [float(i) for i in range(SIZE)]
py_b = [float(i) for i in range(SIZE)]
np_a = np.array(py_a)
np_b = np.array(py_b)

# 1. Element-wise Addition
t0 = time.time()
_ = [py_a[i] + py_b[i] for i in range(SIZE)]
t_list_add = time.time() - t0

t0 = time.time()
_ = np_a + np_b
t_np_add = time.time() - t0

print("=== 1. Element-wise Addition ===")
print(f"  Python list : {t_list_add:.5f}s")
print(f"  NumPy array : {t_np_add:.5f}s")
print(f"  Speedup     : {t_list_add / t_np_add:.1f}x\n")

#2. Element-wise Multiplication
t0 = time.time()
_ = [py_a[i] * py_b[i] for i in range(SIZE)]
t_list_mul = time.time() - t0

t0 = time.time()
_ = np_a * np_b
t_np_mul = time.time() - t0

print("=== 2. Element-wise Multiplication ===")
print(f"  Python list : {t_list_mul:.5f}s")
print(f"  NumPy array : {t_np_mul:.5f}s")
print(f"  Speedup     : {t_list_mul / t_np_mul:.1f}x\n")

#3. Dot Product
t0 = time.time()
dot_py = sum(py_a[i] * py_b[i] for i in range(SIZE))
t_list_dot = time.time() - t0

t0 = time.time()
dot_np = np.dot(np_a, np_b)
t_np_dot = time.time() - t0

print("=== 3. Dot Product ===")
print(f"  Python list : {t_list_dot:.5f}s")
print(f"  NumPy array : {t_np_dot:.5f}s")
print(f"  Speedup     : {t_list_dot / t_np_dot:.1f}x\n")

# 4. Matrix Multiplication (1000x1000)
MAT = 1000
py_mat_a = [[float(i * MAT + j) for j in range(MAT)] for i in range(MAT)]
py_mat_b = [[float(i * MAT + j) for j in range(MAT)] for i in range(MAT)]
np_mat_a = np.array(py_mat_a)
np_mat_b = np.array(py_mat_b)

t0 = time.time()
result_py = [[sum(py_mat_a[i][k] * py_mat_b[k][j]
                  for k in range(MAT))
              for j in range(MAT)]
             for i in range(MAT)]
t_list_mat = time.time() - t0

t0 = time.time()
_ = np_mat_a @ np_mat_b
t_np_mat = time.time() - t0

print("=== 4. Matrix Multiplication (1000x1000) ===")
print(f"  Python list : {t_list_mat:.3f}s")
print(f"  NumPy array : {t_np_mat:.5f}s")
print(f"  Speedup     : {t_list_mat / t_np_mat:.1f}x")

=== 1. Element-wise Addition ===
  Python list : 0.06575s
  NumPy array : 0.00736s
  Speedup     : 8.9x

=== 2. Element-wise Multiplication ===
  Python list : 0.06058s
  NumPy array : 0.00709s
  Speedup     : 8.5x

=== 3. Dot Product ===
  Python list : 0.05356s
  NumPy array : 0.00074s
  Speedup     : 72.3x

=== 4. Matrix Multiplication (1000x1000) ===
  Python list : 102.989s
  NumPy array : 0.06292s
  Speedup     : 1636.8x
